### ISSUE TITLE
Allow the binding address and port to be specified

### ISSUE THREAD

**Issue by gktrk** [aliceinwire/elivepatch-server#3]
Currently, it binds to 0.0.0.0 by default per https://github.com/aliceinwire/elivepatch-server/blob/master/elivepatch_server/elivepatch-server#L40. It should allow the binding address to be specified on the command line.

**Comment by aliceinwire** [comment]
https://github.com/aliceinwire/elivepatch-server/pull/11

**Comment by aliceinwire** [comment]
merged
